version: '2'
services:
  uwazi:
    build:
      context: .
      dockerfile: Dockerfile-development
    ports:
     - "3000:3000"
    depends_on:
     - couchdb
     - elasticsearch
     - logstash
    environment:
     - COUCHDB_URL=http://couchdb:5984
     - ELASTICSEARCH_URL=http://elasticsearch:9200
     - DATABASE_NAME=uwazi_development
     - INDEX_NAME=uwazi_development
     - API_URL=http://localhost:3000
    volumes:
      - .:/opt/uwazi
  couchdb:
    image: klaemo/couchdb
    ports:
     - "5984:5984"
  elasticsearch:
    image: elasticsearch
    ports:
    - "9200:9200"
  logstash:
    image: logstash
    volumes:
      - ./logstash/docker:/config-dir
    depends_on:
     - couchdb
     - elasticsearch
    command: "logstash -f /config-dir/logstash.conf"
